server:
  port: 8080
  host: 0.0.0.0
  db_url: postgres://postgres:postgres@localhost:5432/chat
auth:
  sk: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIA4mh6ctXYftfwRb4je+XyO+D47YNI6ytsmAPpQFq+rt
    -----END PRIVATE KEY-----
  pk: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAXb0Hfuxwr6GN5eMHesm5LmYGATOArNiN7JYQOiDhVag=
    -----END PUBLIC KEY-----
